import { createClient } from 'npm:@supabase/supabase-js@2.95.0';
import { RIFTBATTLE_V2_CARDS } from './cardCatalog.ts';
import { replayRiftBattleV2 } from './serverReplay.ts';
import type { RiftBattleAction, RiftBattleCard } from './types.ts';
import type { RiftBattleDifficulty } from './ai.ts';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Content-Type':'application/json'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:cors});
const score=(cards:RiftBattleCard[])=>cards.reduce((t,c)=>t+c.stats.hp+c.stats.attack*2+c.stats.defense*2+c.deployCost,0);
function hash(s:string){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function opponentFor(playerCards:RiftBattleCard[],seed:string,teamSize:number){const selected=new Set(playerCards.map(c=>c.templateId??c.id));const target=score(playerCards),shift=hash(seed);const candidates=RIFTBATTLE_V2_CARDS.filter(c=>!selected.has(c.id));const ranked=candidates.map((card,index)=>({card,index,distance:Math.abs(target/teamSize-(card.stats.hp+card.stats.attack*2+card.stats.defense*2+card.deployCost))})).sort((a,b)=>a.distance-b.distance||((a.index+shift)%candidates.length)-((b.index+shift)%candidates.length));const result:RiftBattleCard[]=[];for(let offset=0;result.length<teamSize&&offset<ranked.length*2;offset++){const item=ranked[(offset+(shift%ranked.length))%ranked.length];if(!result.some(c=>c.id===item.card.id))result.push(item.card)}return result}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'METHOD_NOT_ALLOWED'},405);try{const auth=req.headers.get('Authorization');if(!auth?.startsWith('Bearer '))return json({error:'AUTH_REQUIRED'},401);const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const userClient=createClient(url,anon,{global:{headers:{Authorization:auth}}});const token=auth.slice(7);const {data:{user},error:userError}=await userClient.auth.getUser(token);if(userError||!user)return json({error:'AUTH_REQUIRED'},401);const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});const body=await req.json();
const expireActive=async(run:any)=>{const actions=Array.isArray(run.events)?run.events:[];const {data:reward,error}=await admin.rpc('settle_riftbattle_v2_run_internal',{p_owner_id:user.id,p_run_id:run.id,p_actions:actions,p_outcome:'DEFEAT'});if(error)throw error;return reward};
const activeRun=async()=>{const {data}=await admin.from('battle_runs').select('id,status,reward_applied,rewards,player_snapshot,npc_snapshot,events,last_activity_at,created_at').eq('owner_id',user.id).eq('status','RUNNING').eq('formula_version','riftbattle-v2-authoritative-v1').order('last_activity_at',{ascending:false}).limit(1).maybeSingle();return data};
if(body?.action==='resume'){const run=await activeRun();if(!run)return json({success:true,active:false});const last=new Date(run.last_activity_at??run.created_at).getTime();if(Date.now()-last>300000){const reward=await expireActive(run);return json({success:true,active:false,expired:true,reward})}await admin.from('battle_runs').update({last_activity_at:new Date().toISOString()}).eq('id',run.id);return json({success:true,active:true,runId:run.id,arena:run.player_snapshot?.arena,playerCards:run.player_snapshot?.cards,opponentCards:run.npc_snapshot?.cards,difficulty:run.player_snapshot?.difficulty,actions:Array.isArray(run.events)?run.events:[],expiresInSeconds:300})}
if(body?.action==='checkpoint'){const runId=String(body.runId??''),actions=body.actions as RiftBattleAction[];if(!Array.isArray(actions)||actions.length>400)return json({error:'INVALID_ACTIONS'},400);const run=await activeRun();if(!run||run.id!==runId)return json({error:'RUN_NOT_FOUND'},404);const last=new Date(run.last_activity_at??run.created_at).getTime();if(Date.now()-last>300000){const reward=await expireActive(run);return json({success:false,expired:true,reward},409)}const playerCards=run.player_snapshot?.cards,opponentCards=run.npc_snapshot?.cards,arena=run.player_snapshot?.arena,difficulty=run.player_snapshot?.difficulty as RiftBattleDifficulty;if(!Array.isArray(playerCards)||!Array.isArray(opponentCards)||!arena)throw new Error('RUN_SNAPSHOT_INVALID');replayRiftBattleV2(playerCards,opponentCards,arena,difficulty,actions);await admin.from('battle_runs').update({events:actions,last_activity_at:new Date().toISOString()}).eq('id',run.id).eq('owner_id',user.id).eq('status','RUNNING');return json({success:true,expiresInSeconds:300})}
if(body?.action==='start'){const existing=await activeRun();if(existing){const last=new Date(existing.last_activity_at??existing.created_at).getTime();if(Date.now()-last<=300000)return json({error:'ACTIVE_RUN_EXISTS',resumable:true},409);await expireActive(existing)}const requestId=String(body.requestId??''),arenaId=String(body.arenaId??''),difficulty=String(body.difficulty??'OPERADOR') as RiftBattleDifficulty,instanceIds=Array.isArray(body.instanceIds)?body.instanceIds.map(String):[];if(!['RECRUTA','OPERADOR','NEXUS'].includes(difficulty))return json({error:'INVALID_DIFFICULTY'},400);const {data:receipt,error:validationError}=await userClient.rpc('validate_riftbattle_v2_squad',{p_request_id:requestId,p_arena_id:arenaId,p_rules_version:'riftbattle-v2-preview-20260922.1',p_instance_ids:instanceIds});if(validationError||!receipt?.success||!receipt?.arena||!Array.isArray(receipt?.cards))return json({error:'SQUAD_VALIDATION_FAILED'},400);const opponentCards=opponentFor(receipt.cards,requestId,receipt.arena.teamSize);const {data:run,error:runError}=await admin.rpc('start_riftbattle_v2_run_internal',{p_owner_id:user.id,p_request_id:requestId,p_arena:receipt.arena,p_player_cards:receipt.cards,p_opponent_cards:opponentCards,p_difficulty:difficulty});if(runError)throw runError;return json({success:true,runId:run.id,requestId,arena:receipt.arena,playerCards:receipt.cards,opponentCards,difficulty})}if(body?.action==='finish'){const runId=String(body.runId??''),actions=body.actions as RiftBattleAction[];if(!Array.isArray(actions)||actions.length>400)return json({error:'INVALID_ACTIONS'},400);const {data:run,error:runError}=await admin.from('battle_runs').select('id,owner_id,status,reward_applied,rewards,player_snapshot,npc_snapshot').eq('id',runId).eq('owner_id',user.id).single();if(runError||!run)return json({error:'RUN_NOT_FOUND'},404);if(run.reward_applied)return json({success:true,idempotent:true,reward:run.rewards});const playerCards=run.player_snapshot?.cards,opponentCards=run.npc_snapshot?.cards,arena=run.player_snapshot?.arena,difficulty=run.player_snapshot?.difficulty as RiftBattleDifficulty;if(!Array.isArray(playerCards)||!Array.isArray(opponentCards)||!arena)throw new Error('RUN_SNAPSHOT_INVALID');const finalState=replayRiftBattleV2(playerCards,opponentCards,arena,difficulty,actions);if(finalState.phase!=='FINISHED'||!finalState.result)return json({error:'MATCH_NOT_FINISHED'},409);const outcome=finalState.result.winnerId==='PLAYER_ONE'?'VICTORY':'DEFEAT';const {data:reward,error:rewardError}=await admin.rpc('settle_riftbattle_v2_run_internal',{p_owner_id:user.id,p_run_id:runId,p_actions:actions,p_outcome:outcome});if(rewardError)throw rewardError;return json({success:true,idempotent:false,outcome,reward})}return json({error:'INVALID_ACTION'},400)}catch(error){console.error(error);return json({error:'RIFTBATTLE_V2_SERVER_ERROR'},500)}});
