-- Lightweight anonymous signup funnel analytics.
-- No email, username, password, IP address, or other account PII is stored.

create table if not exists public.funnel_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_name text not null check (event_name in (
    'landing_view',
    'register_open',
    'register_submit',
    'register_success',
    'register_error'
  )),
  session_id text not null check (char_length(session_id) between 8 and 80),
  source text,
  path text,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists funnel_events_created_at_idx
  on public.funnel_events (created_at desc);
create index if not exists funnel_events_event_name_created_at_idx
  on public.funnel_events (event_name, created_at desc);

alter table public.funnel_events enable row level security;

revoke all on table public.funnel_events from anon, authenticated;
grant select, insert, update, delete on table public.funnel_events to service_role;

create or replace function public.track_funnel_event(
  p_event_name text,
  p_session_id text,
  p_source text default null,
  p_path text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if p_event_name not in ('landing_view','register_open','register_submit','register_success','register_error') then
    raise exception 'invalid funnel event';
  end if;

  if p_session_id is null or char_length(p_session_id) < 8 or char_length(p_session_id) > 80 then
    raise exception 'invalid session id';
  end if;

  insert into public.funnel_events(event_name, session_id, source, path, metadata)
  values (
    p_event_name,
    p_session_id,
    left(nullif(p_source, ''), 100),
    left(nullif(p_path, ''), 300),
    coalesce(p_metadata, '{}'::jsonb)
  );
end;
$$;

revoke all on function public.track_funnel_event(text,text,text,text,jsonb) from public;
grant execute on function public.track_funnel_event(text,text,text,text,jsonb) to anon, authenticated, service_role;
